// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telerik_SampleProject.Database;

namespace Telerik_SampleProject.Migrations
{
    [DbContext(typeof(DatabaseConntext))]
    partial class DatabaseConntextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Telerik_SampleProject.Model.RegistrationModel", b =>
                {
                    b.Property<int>("RegistrationModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Reg_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Reg_Age");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reg_City");

                    b.Property<bool>("CivilStatus")
                        .HasColumnType("bit")
                        .HasColumnName("Reg_CivilStatus");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reg_FirstName");

                    b.Property<string>("Langudage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reg_Language");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Reg_Name");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Reg_Date");

                    b.Property<bool>("Subscription")
                        .HasColumnType("bit")
                        .HasColumnName("Reg_Subscription");

                    b.HasKey("RegistrationModelID");

                    b.ToTable("RegistrationMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
